require("config.lazy")
require("config.cmp")
require("config.lsp-zero")
require("config.treesitter")
require("config.fugitive")
require("config.dap")
require("config.neotree")
require("config.hop")
require("config.telescope")

require("config.set")
require("config.remap")
